### ISSUE TITLE
openimages and model.zip can't download!

### ISSUE THREAD

**Issue by ktg4929** [umr-ds/ElasticHash#1]
hi!

openimages and model.zip can't download!

https://hessenbox.uni-marburg.de/dl/fiHXWDeNCt5GN3RuX8sru/model.zip

https://hessenbox.uni-marburg.de/dl/fiHjZrgFkb6P6yLFpoFn1X/oi_codes.tar.gz

plz check!

thanks.

**Comment by nik-ko** [comment]
Thanks for the hint.
I have temporarily extended the links and will soon publish the data on another server.
